version: "3.3"

services:
  backend-fa:
    build: .
    container_name: backend-fa
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/build"
    env_file:
      - .env
    depends_on:
      - postgres-fa

  postgres-fa:
    image: postgres:13.4-alpine
    container_name: postgres-fa
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data_zoom:/var/lib/postgresql/data

  pgadmin-fa:
    image: dpage/pgadmin4:5.6
    container_name: pgadmin-fa
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - postgres-fa
    links:
      - postgres-fa

volumes:
  db_data_zoom: {}