version: "3.3"

services:
  backend:
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/build"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.6
    container_name: pgadmin
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  db_data: {}