"""Added required table

Revision ID: d00eca5252f0
Revises: 
Create Date: 2021-09-15 19:38:31.098751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00eca5252f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_ts', sa.BigInteger(), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoom_events')
    # ### end Alembic commands ###
